config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# This is a basic HomeController with an index that does one thig: render 
# the view file associated with the controller action

class HomeController < ApplicationController
    def index
        render
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>

  </head>
  
  <body>
    <div style="margin: 5% 0 0 10%;">
    <h1>Projects</h1>   
    <h1>CS 3300 Portfolio Project - Fall 2022</h1>

      <div style="padding-left: 2rem;">
       <h4 style="color: blue"> jasonCuthbert </h3>
        <p style="color: green"><%= notice %></p>

        <!--- Explain what the block of code below this line is doing --->

        <% if user_signed_in? %>
          
          <div> Welcome <%= current_user.email %> </div>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
        
        <% else %>
          <a href="/users/sign_in"> Sign in</a>
        <% end %>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300fall2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>
    <style>
        .notice {
            color: dark;   margin: auto;
        }
        .project {
            justify-content: center;
        }
        .card {
            background-color: gray;
            margin-right:20px!important
            color: orange;
        }
        form.label {
            width: 75%;
            height: 170px;
        }
    </style>
</head>

<body class="bg-dark">
    <br> </br>
    <div class="container p-4 text-white">
        <!--- Explain what the block of code below this line is doing --->
        <div class="d-flex">
            <div class="justify-content-start align-items-start">
                <%= link_to "Back to projects", projects_path , class: "btn btn-primary text-dark  bg-light"%>
            </div>
            <div class="col  d-flex justify-content-end align-items-start">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary text-dark  bg-light"%>
            </div>
        </div>
        <div style="text-align: center;">
            <%= form_with(model: project) do |form| %>
                <% if project.errors.any? %>
                    <div style="color: red">
                        <h2>
                            <%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

                        <ul>
                            <% project.errors.each do |error| %>
                                <li>
                                    <%= error.full_message %>
                                </li>
                                <% end %>
                        </ul>
                    </div>
                    <% end %>
                        <div>
                            <%= form.label :title, style: "display: block" %>
                                <%= form.text_field :title %>
                        </div>

                        <div>
                            <%= form.label :description, style: "display: block" %>
                                <%= form.text_area :description, :size=>"30", :maxlength=>"254" %>
                        </div>

                        <div>
                            <%= form.submit %>
                        </div>
                        <% end %>
        </div>
    </div>
    <footer class="bg-dark fixed-bottom">
        <div class="d-flex">
            <div class="col  d-flex justify-content-around">

                <button onclick="window.location='http://www.github.com/jcuberdruid';" type="button" class="btn btn-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width=48" height="48" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
              </svg>
              </button>

                <a href="mailto:jason@fastmail.org" title ">
              <svg xmlns="http://www.w3.org/2000/svg " width=46" height="46" fill="grey" viewBox="0 0 512 512">
                    <path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z">
                    </path>
                    </svg>
                </a>

            </div>
        </div>
        </div>
    </footer>
</body>

</html>

app/views/projects/_project.html.erb
<div class="project" id="<%= dom_id project %>">

<div class="card-body">

  <h5 class="card-title"> <%= project.title %> </h5>
  <p class="card-text"> <%= project.description %> </p>
  

  
</div>
</div>

app/views/projects/edit.html.erb
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>
    <style>
        .notice {
              color: orange;
          }
          .project {
              justify-content: center;
          }
          .card{
              background-color: gray;
              margin-right:20px!important
          }
          .card p{
            min-width: 300px; 
            max-width: 300px; 
    
          }
          .d-flex{
              gap:20px;
          }
    </style>
</head>

<body class="bg-dark">
    <div class="container p-4 bg-dark text-white" style="width: auto;">
        <!--- Explain what the block of code below this line is doing --->
        <% if user_signed_in? %>
            <div> Welcome
                <%= current_user.email %>
            </div>
            <div class="col  d-flex justify-content-end align-items-start">
                <%= link_to "New project", new_project_path , class: "btn btn-primary text-dark  bg-light"%>
                    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary text-dark  bg-light"%>
                        <% else %>
                            <div>ㅤㅤㅤ </div>
                            <div class="col  d-flex justify-content-end align-items-start">
                                <%= link_to "Sign In", "/users/sign_in" , class: "btn btn-primary text-dark  bg-light"%>
                                    <% end %>

                            </div>
                            <div class="page-header">
                                <h1>CS 3300 Portfolio Project - Fall 2022</h1>
                            </div>
                            <p> Hello! I'm a <a href="https://eas.uccs.edu/cs/academics/undergraduate-programs/bachelor-of-science-in-computer-science">CS </a> student at UCCS in Colorado</p>
            </div>
            <div>
                <div>
                </div>
                <div class="container p-4">
                    <div class="d-flex flex-wrap justify-content-center">
                        <% @projects.each do |project| %>
                            <div class="card w-30 m-1">
                                <%= render project %>
                                    <%= link_to "Show this project", project , class: "mt-auto btn btn-info" %>
                            </div>
                            <% end %>
                    </div>
                </div>
            </div>
            <br></br>
            <footer class="bg-dark fixed-bottom">
                <div class="d-flex">
                    <div class="col  d-flex justify-content-around">

                        <button onclick="window.location='http://www.github.com/jcuberdruid';" type="button" class="btn btn-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width=48" height="48" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
              </svg>
              </button>

                        <a href="mailto:jason@fastmail.org" title ">
              <svg xmlns="http://www.w3.org/2000/svg " width=46" height="46" fill="grey" viewBox="0 0 512 512">
                            <path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z">
                            </path>
                            </svg>
                        </a>

                    </div>
                </div>
    </div>
    </footer>
</body>

</html>

app/views/projects/new.html.erb
<%= render "form", project: @project %>

app/views/projects/show.html.erb
<<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CS3300 Portfolio Project</title>
    <style>
        .notice {
              color: orange;
          }
          .project {
              justify-content: center;
          }
          .card{
              margin-right:20px!important
              color: orange;
          }
    </style>
    </head>

    <body class="bg-dark">

        <div class="container p-4 text-white" style="width: auto;">
            <!--- Explain what the block of code below this line is doing --->
            <div class="d-flex">
                <% if user_signed_in? %>
                    <div class="justify-content-start align-items-start">
                        <%= link_to "Back to projects", projects_path , class: "btn btn-primary text-dark  bg-light"%>
                    </div>
                    <div class="col  d-flex justify-content-end align-items-start">
                        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary text-dark  bg-light"%>
                    </div>
                    <% else %>
                        <div class="col  d-flex justify-content-start align-items-start">
                            <%= link_to "Back to projects", projects_path , class: "btn btn-primary text-dark  bg-light"%>
                        </div>
                        <div class="col  d-flex justify-content-end align-items-start">
                            <%= link_to "Sign In", "/users/sign_in" , class: "btn btn-primary text-dark  bg-light"%>
                        </div>
                        <% end %>
            </div>

            <br></br>

            <!--<p style="color: green"><%= notice %></p>--->

            <div class="card bg-info" style="width: auto;">
                <%= render @project %>
            </div>

            <br></br>
            
            <div>
                <% if user_signed_in? %>
                    <%= link_to "Edit this project", edit_project_path(@project) , class: "btn btn-primary text-dark  bg-light" %>
                        <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger" %>
                            <% end %>
            </div>

            <footer class="bg-dark fixed-bottom">
                <div class="d-flex">
                    <div class="col  d-flex justify-content-around">

                        <button onclick="window.location='http://www.github.com/jcuberdruid';" type="button" class="btn btn-secondary">
              <svg xmlns="http://www.w3.org/2000/svg" width=48" height="48" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
              </svg>
              </button>

                        <a href="mailto:jason@fastmail.org" title ">
              <svg xmlns="http://www.w3.org/2000/svg " width=46" height="46" fill="grey" viewBox="0 0 512 512">
                            <path d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z">
                            </path>
                            </svg>
                        </a>

                    </div>
                </div>
        </div>
        </footer>
    </body>

    </html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>